spring:
    freemarker:
        template-loader-path: file:///D:/Space/InclusivePlatform/term/src/main/resources/templates
        cache: false
        prefer-file-system-access: true
    web:
        resources:
            chain:
                cache: false
    server:
        error:
            path: "/error"
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:postgresql:lecturesDB
        username: postgres
        password: admin